### ISSUE TITLE
MNT: iron out tree serialization, add examples to tests

### ISSUE THREAD

**Issue by tangkong** [pcdshub/BEAMS#18]
Serialization is jumping through some strange hoops, with quite a few dataclasses that don't seem to be one-to-one with behavior tree node types.  For the sake of transparency and user understanding, these should be as analogous as possible

If we are using apischema, it might make sense to port over the as_tagged_union stuff that we have used elsewhere

Tests should probably hold an example or two, for demonstration purposes  (and for future developers)

**Comment by tangkong** [comment]
Critically this should enable "recursive tree generation" (or trees with more than one level of children).

**Comment by joshc-slac** [comment]
I would like to tag team at least the brainstorming part of this one with you. I definitely, definitely need your help with the apischema encoding of these nodes which is currently subpar. 

As it seems you allude to addressing this issue will act as  a forcing function to address that the meat of this work function should live in a much more intentional organized place: https://github.com/pcdshub/BEAMS/blob/c4a247a07f482609d1f2cca33af637bd707d7107/beams/tree_generator/TreeSerializer.py#L88-L102 

In the current structure the "recursive" part would be intended to live here:
https://github.com/pcdshub/BEAMS/blob/c4a247a07f482609d1f2cca33af637bd707d7107/beams/tree_generator/TreeSerializer.py#L130-L140

But that would require changes either enabling `CheckAndDoNode` to have children of type `CheckAndDoNode` or to enable `TreeSpec.children` to take `CheckAndDoNode` children and `TreeSpec` children. I agree semantically and organizationally this is rough so we should definitely improve it.

**Comment by tangkong** [comment]
I'll take a pass at CI early next week and then try to get to this.  I'll coordinate with you to maybe pair-code this up 👍
